[package]
name = "templateless"
description = "Ship faster by sending elegant emails using just code"
repository = "https://github.com/templateless/templateless-rust"
documentation = "https://docs.rs/templateless"
homepage = "https://templateless.com/"
version = "0.1.0-alpha.5"
license = "MIT"
edition = "2021"
readme = "README.md"
keywords = ["email", "templates"]

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.57"
reqwest = { version = "0.11.24", features = ["rustls-tls", "json"] }
tokio = { version = "1.36.0", features = ["full"] }
erased-serde = "0.4.3"
dotenvy = "0.15.7"
exitcode = "1.1.2"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "confirm_email"
path = "examples/confirm_email.rs"
