[package]
name = "templateless"
description = "Ship faster by sending elegant emails using just code"
repository = "https://github.com/templateless/templateless-rust"
documentation = "https://docs.rs/templateless"
homepage = "https://templateless.com/"
version = "0.1.0-alpha.2"
license = "MIT"
edition = "2021"
readme = "README.md"
keywords = ["email", "templates"]

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.112"
thiserror = "1.0.56"
reqwest = { version = "0.11.23", features = ["rustls-tls", "json"] }
tokio = { version = "1.35.1", features = ["full"] }
http = "1.0.0"
erased-serde = "0.4.2"
dotenvy = "0.15.7"
exitcode = "1.1.2"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "confirm_email"
path = "examples/confirm_email.rs"
