[package]
name = "templateless"
version = "0.1.0-alpha.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
thiserror = "1.0.56"
reqwest = { version = "0.11.23", features = ["rustls-tls", "json"] }
tokio = { version = "1.35.1", features = ["full"] }
http = "1.0.0"
erased-serde = "0.4.2"
dotenvy = "0.15.7"
exitcode = "1.1.2"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "confirm_email"
path = "examples/confirm_email.rs"
